### PR TITLE
Exclude self from mention & reply highlights

### LINKED ISSUE #654: [BUG] Mention highlight when tagging myself or replying to someone that replied to me
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Opera

### Current Behavior

I get a mention highlight when replying to someone that replied to me or when I @ myself

### Expected Behavior

I expect to not get a mention highlight when replying to someone that replied to me or when I @ myself

### Steps To Reproduce

Have mention highlights turned on and @ yourself or reply to someone who replied to one of your messages

### PR DESCRIPTION
**Pull request by 2547techno**
Fixes #654

Do not highlight messages as "reply" if message and parent message are from yourself (ie. sending a message in a thread starting from your own message)

Ignore mentions from yourself

~~This PR also allows the use of the `test` arg even when a regex patter is defined. If both a pattern and a test are defined, the result is AND'd. If only a test is defined, the result is the result of the test~~

### CODE REVIEW

File: src/composable/chat/useChatHighlights.ts [hunk 1]
```diff
@@ -168,8 +169,13 @@ export function useChatHighlights(ctx: ChannelContext) {
...
 				: msg.body.toLowerCase().includes(h.pattern.toLowerCase());
-		} else if (typeof h.test === "function") {
-			ok = h.test(msg);
+		} else {
+			justTest = true;
+		}
+
+		if (typeof h.test === "function") {
+			const t = h.test(msg);
+			ok = justTest ? t : ok && t;
```
Comment (AnatoleAM) [inline src/composable/chat/useChatHighlights.ts:178]: What is the purpose of this?

Comment (2547techno) [reply src/composable/chat/useChatHighlights.ts:178]: When defining a `chatHighligh`, if `regexp`/`pattern` are defined, you can still define `test`, both must pass to return `true` for `checkMatch`.

Originally if both were defined, `test` would be ignored due to the `else if`

Comment (AnatoleAM) [reply src/composable/chat/useChatHighlights.ts:178]: That doesn't seem useful, there is no reason I can think of where it would be desirable to have both a pattern and a test function. The latter is capable of doing the former anyway.

Comment (2547techno) [reply src/composable/chat/useChatHighlights.ts]: Changes made
